import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787354441945 implements MigrationInterface {
    name = 'InitialSchema1787354441945'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module" character varying NOT NULL, "action" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "houses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "password" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee6cacb502a4b8590005eb3dc8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "name" character varying NOT NULL, "password" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "active_house_id" character varying, "plan" character varying NOT NULL DEFAULT 'free', "last_login_at" TIMESTAMP, "reset_token" character varying, "reset_token_expiry" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('ingreso_fijo', 'ingreso_variable', 'gasto')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_paymentmethod_enum" AS ENUM('efectivo', 'transferencia', 'tarjeta')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."transactions_type_enum" NOT NULL, "concept" character varying NOT NULL, "category" character varying, "amount" numeric(12,2) NOT NULL, "paymentMethod" "public"."transactions_paymentmethod_enum" NOT NULL DEFAULT 'efectivo', "cardName" character varying, "date" date NOT NULL, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d66471a99dd3836e1528d39a1e" ON "transactions" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f24c67b2a439614e058bf5598a" ON "transactions" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "savings_goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "goalAmount" numeric(12,2) NOT NULL DEFAULT '0', "currentSavings" numeric(12,2) NOT NULL DEFAULT '0', "months" integer NOT NULL DEFAULT '12', "annualInterestRate" numeric(5,4) NOT NULL DEFAULT '0', "emoji" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_4f1e133521cfbf2b4252bd8f09d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0c000b88df1ee31bbbeb5e24c" ON "savings_goals" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "recurring_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "amount" numeric(12,2) NOT NULL DEFAULT '0', "category" character varying, "dayOfMonth" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "lastGeneratedAt" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_6485db3243762a54992dc0ce3b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41139b4264055882aa0675c208" ON "recurring_transactions" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpoint" text NOT NULL, "keys" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid NOT NULL, CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c3a113119a02c1d82cf269c5d" ON "push_subscriptions" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "purchase_lists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "budget" numeric(12,2) NOT NULL DEFAULT '0', "baseCurrencyCode" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_217cbe31c6d830cc4c303220772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_items_status_enum" AS ENUM('pending', 'purchased', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "quantity" numeric(10,2) NOT NULL DEFAULT '0', "unitPrice" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying, "lugar" character varying, "status" "public"."purchase_items_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "list_id" uuid, CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "net_worth_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "snapshotDate" date NOT NULL, "totalAssets" numeric(14,2) NOT NULL, "totalLiabilities" numeric(14,2) NOT NULL, "netWorth" numeric(14,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_c8fa90bccd2310ccf90e3788287" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2f1125d451a51dc5c61a41459" ON "net_worth_snapshots" ("house_id") `);
        await queryRunner.query(`CREATE TYPE "public"."investments_type_enum" AS ENUM('plazo_fijo', 'fci', 'acciones', 'crypto', 'dolar', 'propiedades', 'otros')`);
        await queryRunner.query(`CREATE TYPE "public"."investments_currency_enum" AS ENUM('ARS', 'USD', 'CUP')`);
        await queryRunner.query(`CREATE TABLE "investments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."investments_type_enum" NOT NULL DEFAULT 'otros', "amount" numeric(15,2) NOT NULL, "currency" "public"."investments_currency_enum" NOT NULL DEFAULT 'ARS', "annualRate" numeric(8,4) NOT NULL DEFAULT '0', "startDate" date, "endDate" date, "notes" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid NOT NULL, CONSTRAINT "PK_a1263853f1a4fb8b849c1c9aff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d4bbea81db025cc9549d5248d7" ON "investments" ("house_id") `);
        await queryRunner.query(`CREATE TYPE "public"."household_expenses_category_enum" AS ENUM('Comida', 'Transporte', 'Hogar', 'Salud', 'Ocio', 'Salidas', 'Shopper', 'Otros')`);
        await queryRunner.query(`CREATE TABLE "household_expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "description" character varying NOT NULL, "category" "public"."household_expenses_category_enum" NOT NULL DEFAULT 'Otros', "amountCUP" numeric(12,2) NOT NULL DEFAULT '0', "place" character varying, "month" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_c5d6dfd52c18386b9477e6c31f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97c66324f4b349a5aca2b564fb" ON "household_expenses" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_b78d4c319ee3a47c039bc8544c" ON "household_expenses" ("month") `);
        await queryRunner.query(`CREATE INDEX "IDX_2fe1108e5be68571ac19022783" ON "household_expenses" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loanType" character varying NOT NULL, "institution" character varying NOT NULL, "initialDebt" numeric(12,2) NOT NULL DEFAULT '0', "currentDebt" numeric(12,2) NOT NULL DEFAULT '0', "monthlyPayment" numeric(12,2) NOT NULL DEFAULT '0', "notes" character varying, "paymentDay" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_5c6942c1e13e4de135c5203ee61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4276c9fb53c98d03f15341ff26" ON "loans" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "house_currencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "currencyCode" character varying NOT NULL, "currencyName" character varying NOT NULL, "symbol" character varying NOT NULL, "locale" character varying NOT NULL DEFAULT 'en-US', "isBase" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_069267d0e8267655042c95e058d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5cf0463d99c166546f7af395b5" ON "house_currencies" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "exchange_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fromCurrency" character varying NOT NULL, "toCurrency" character varying NOT NULL, "rate" numeric(15,4) NOT NULL, "date" date NOT NULL, "source" character varying, "rateType" character varying NOT NULL DEFAULT 'oficial', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_33a614bad9e61956079d817ebe2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "emergency_funds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "targetMonths" integer NOT NULL DEFAULT '6', "minimumMonths" integer NOT NULL DEFAULT '3', "savingPeriodMonths" integer NOT NULL DEFAULT '24', "currentBalance" numeric(12,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_177efca3a0beb16c0f7aaa4191f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee734c37dc94b8500d8a40d29f" ON "emergency_funds" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "expense_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "monthlyAmount" numeric(12,2) NOT NULL DEFAULT '0', "sortOrder" integer NOT NULL DEFAULT '0', "fund_id" uuid, CONSTRAINT "PK_d0ef31e189d9523461215b62775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."debts_type_enum" AS ENUM('they_owe_me', 'i_owe')`);
        await queryRunner.query(`CREATE TABLE "debts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "personName" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "note" character varying, "type" "public"."debts_type_enum" NOT NULL, "interestRate" numeric(8,4) NOT NULL DEFAULT '0', "minimumPayment" numeric(12,2), "isPaid" boolean NOT NULL DEFAULT false, "paidAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_4bd9f54aab9e59628a3a2657fa1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0278fdedafa9ab24bfc0b0aa6e" ON "debts" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "cuotas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "totalAmount" numeric(12,2) NOT NULL, "totalInstallments" integer NOT NULL, "paidInstallments" integer NOT NULL, "installmentAmount" numeric(12,2) NOT NULL, "store" character varying, "cardLast4" character varying, "startDate" date NOT NULL, "withInterest" boolean NOT NULL DEFAULT false, "interestRate" numeric(5,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_fb728d76452f13f226db1943bdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e70b8513c88f595b9f83749bcb" ON "cuotas" ("house_id") `);
        await queryRunner.query(`CREATE TYPE "public"."credit_cards_paymenttype_enum" AS ENUM('full', 'minimum', 'stopped', 'partial')`);
        await queryRunner.query(`CREATE TABLE "credit_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bankName" character varying NOT NULL, "cardName" character varying NOT NULL, "annualRate" numeric(5,4) NOT NULL DEFAULT '0', "currentBalance" numeric(12,2) NOT NULL DEFAULT '0', "creditLimit" numeric(12,2) NOT NULL DEFAULT '0', "cutDate" character varying, "paymentDate" character varying, "paymentType" "public"."credit_cards_paymenttype_enum" NOT NULL DEFAULT 'full', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_7749b596e358703bb3dd8b45b7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50e41ba6f48cd56959d48b9891" ON "credit_cards" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL DEFAULT 'Mi Presupuesto', "year" integer, "savingsTargetPercent" numeric(5,2) NOT NULL DEFAULT '20', "rule" character varying(16) NOT NULL DEFAULT '50-30-20', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_431fac525c60f41aeed92bf55c" ON "budgets" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "budget_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "budget_id" uuid, CONSTRAINT "PK_2159c4d6372542f4629c4149045" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_919faa73fd59efb0f80ccc3607" ON "budget_categories" ("budget_id") `);
        await queryRunner.query(`CREATE TYPE "public"."budget_expenses_periodicity_enum" AS ENUM('daily', 'weekly', 'biweekly', 'monthly', 'bimonthly', 'quarterly', 'fourmonthly', 'semiannual', 'annual')`);
        await queryRunner.query(`CREATE TABLE "budget_expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "amount" numeric(12,2) NOT NULL DEFAULT '0', "periodicity" "public"."budget_expenses_periodicity_enum" NOT NULL DEFAULT 'monthly', "isFixed" boolean NOT NULL DEFAULT false, "isCreditCard" boolean NOT NULL DEFAULT false, "isAntExpense" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "category_id" uuid, CONSTRAINT "PK_3d7b40c7bd67f77175758102753" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a27359168c75df14b4dd4655f" ON "budget_expenses" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "income_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'fixed', "amount" numeric(12,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "budget_id" uuid, CONSTRAINT "PK_5e2bc8bfe0ee6a3e4726bdf0d79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b9eafaf7b77cd42d38373baa6" ON "income_sources" ("budget_id") `);
        await queryRunner.query(`CREATE TYPE "public"."assets_assettype_enum" AS ENUM('physical', 'cash')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "value" numeric(12,2) NOT NULL DEFAULT '0', "assetType" "public"."assets_assettype_enum" NOT NULL DEFAULT 'physical', "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "house_id" uuid, CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_929b26168da1133020fec9dfc6" ON "assets" ("house_id") `);
        await queryRunner.query(`CREATE TABLE "app_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message" character varying NOT NULL, "title" character varying, "body" character varying, "type" character varying NOT NULL DEFAULT 'sistema', "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "houseId" character varying NOT NULL, "house_id" uuid, CONSTRAINT "PK_4ff08fe3c2ebf2593490403bbe0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_24e8d943aab12b2cc91e2d1616" ON "app_notifications" ("houseId") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("rolesId" uuid NOT NULL, "permissionsId" uuid NOT NULL, CONSTRAINT "PK_7931614007a93423204b4b73240" PRIMARY KEY ("rolesId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0cb93c5877d37e954e2aa59e52" ON "role_permissions" ("rolesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d422dabc78ff74a8dab6583da0" ON "role_permissions" ("permissionsId") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("usersId" uuid NOT NULL, "rolesId" uuid NOT NULL, CONSTRAINT "PK_38ffcfb865fc628fa337d9a0d4f" PRIMARY KEY ("usersId", "rolesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99b019339f52c63ae615358738" ON "user_roles" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13380e7efec83468d73fc37938" ON "user_roles" ("rolesId") `);
        await queryRunner.query(`CREATE TABLE "user_houses" ("user_id" uuid NOT NULL, "house_id" uuid NOT NULL, CONSTRAINT "PK_ab396e31e360b850a5b6d071878" PRIMARY KEY ("user_id", "house_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_79236188200321130a73610425" ON "user_houses" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d50568d05ba4085419ac313fa4" ON "user_houses" ("house_id") `);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_f24c67b2a439614e058bf5598ad" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "savings_goals" ADD CONSTRAINT "FK_a0c000b88df1ee31bbbeb5e24cb" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" ADD CONSTRAINT "FK_41139b4264055882aa0675c2082" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_3c3a113119a02c1d82cf269c5dc" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_lists" ADD CONSTRAINT "FK_cb46e343e81a9fdd86f75af8fd7" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_dcf5767533659f4c2a4bd1953cf" FOREIGN KEY ("list_id") REFERENCES "purchase_lists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "net_worth_snapshots" ADD CONSTRAINT "FK_b2f1125d451a51dc5c61a41459e" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investments" ADD CONSTRAINT "FK_d4bbea81db025cc9549d5248d77" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "household_expenses" ADD CONSTRAINT "FK_2fe1108e5be68571ac190227831" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_4276c9fb53c98d03f15341ff26a" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "house_currencies" ADD CONSTRAINT "FK_5cf0463d99c166546f7af395b53" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emergency_funds" ADD CONSTRAINT "FK_ee734c37dc94b8500d8a40d29f0" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ADD CONSTRAINT "FK_87092648b0d881ed5e9bfdff70e" FOREIGN KEY ("fund_id") REFERENCES "emergency_funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debts" ADD CONSTRAINT "FK_0278fdedafa9ab24bfc0b0aa6ee" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cuotas" ADD CONSTRAINT "FK_e70b8513c88f595b9f83749bcbf" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_cards" ADD CONSTRAINT "FK_50e41ba6f48cd56959d48b98915" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_431fac525c60f41aeed92bf55c2" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_categories" ADD CONSTRAINT "FK_919faa73fd59efb0f80ccc36079" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_expenses" ADD CONSTRAINT "FK_8a27359168c75df14b4dd4655fc" FOREIGN KEY ("category_id") REFERENCES "budget_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "income_sources" ADD CONSTRAINT "FK_5b9eafaf7b77cd42d38373baa6e" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_929b26168da1133020fec9dfc60" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ADD CONSTRAINT "FK_706bd9f060e23d8e347ee6211a2" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_d422dabc78ff74a8dab6583da02" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_99b019339f52c63ae6153587380" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_13380e7efec83468d73fc37938e" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_houses" ADD CONSTRAINT "FK_79236188200321130a736104258" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_houses" ADD CONSTRAINT "FK_d50568d05ba4085419ac313fa40" FOREIGN KEY ("house_id") REFERENCES "houses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_houses" DROP CONSTRAINT "FK_d50568d05ba4085419ac313fa40"`);
        await queryRunner.query(`ALTER TABLE "user_houses" DROP CONSTRAINT "FK_79236188200321130a736104258"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_13380e7efec83468d73fc37938e"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_99b019339f52c63ae6153587380"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_d422dabc78ff74a8dab6583da02"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c"`);
        await queryRunner.query(`ALTER TABLE "app_notifications" DROP CONSTRAINT "FK_706bd9f060e23d8e347ee6211a2"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_929b26168da1133020fec9dfc60"`);
        await queryRunner.query(`ALTER TABLE "income_sources" DROP CONSTRAINT "FK_5b9eafaf7b77cd42d38373baa6e"`);
        await queryRunner.query(`ALTER TABLE "budget_expenses" DROP CONSTRAINT "FK_8a27359168c75df14b4dd4655fc"`);
        await queryRunner.query(`ALTER TABLE "budget_categories" DROP CONSTRAINT "FK_919faa73fd59efb0f80ccc36079"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_431fac525c60f41aeed92bf55c2"`);
        await queryRunner.query(`ALTER TABLE "credit_cards" DROP CONSTRAINT "FK_50e41ba6f48cd56959d48b98915"`);
        await queryRunner.query(`ALTER TABLE "cuotas" DROP CONSTRAINT "FK_e70b8513c88f595b9f83749bcbf"`);
        await queryRunner.query(`ALTER TABLE "debts" DROP CONSTRAINT "FK_0278fdedafa9ab24bfc0b0aa6ee"`);
        await queryRunner.query(`ALTER TABLE "expense_categories" DROP CONSTRAINT "FK_87092648b0d881ed5e9bfdff70e"`);
        await queryRunner.query(`ALTER TABLE "emergency_funds" DROP CONSTRAINT "FK_ee734c37dc94b8500d8a40d29f0"`);
        await queryRunner.query(`ALTER TABLE "house_currencies" DROP CONSTRAINT "FK_5cf0463d99c166546f7af395b53"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_4276c9fb53c98d03f15341ff26a"`);
        await queryRunner.query(`ALTER TABLE "household_expenses" DROP CONSTRAINT "FK_2fe1108e5be68571ac190227831"`);
        await queryRunner.query(`ALTER TABLE "investments" DROP CONSTRAINT "FK_d4bbea81db025cc9549d5248d77"`);
        await queryRunner.query(`ALTER TABLE "net_worth_snapshots" DROP CONSTRAINT "FK_b2f1125d451a51dc5c61a41459e"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_dcf5767533659f4c2a4bd1953cf"`);
        await queryRunner.query(`ALTER TABLE "purchase_lists" DROP CONSTRAINT "FK_cb46e343e81a9fdd86f75af8fd7"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_3c3a113119a02c1d82cf269c5dc"`);
        await queryRunner.query(`ALTER TABLE "recurring_transactions" DROP CONSTRAINT "FK_41139b4264055882aa0675c2082"`);
        await queryRunner.query(`ALTER TABLE "savings_goals" DROP CONSTRAINT "FK_a0c000b88df1ee31bbbeb5e24cb"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_f24c67b2a439614e058bf5598ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d50568d05ba4085419ac313fa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79236188200321130a73610425"`);
        await queryRunner.query(`DROP TABLE "user_houses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13380e7efec83468d73fc37938"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99b019339f52c63ae615358738"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d422dabc78ff74a8dab6583da0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb93c5877d37e954e2aa59e52"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24e8d943aab12b2cc91e2d1616"`);
        await queryRunner.query(`DROP TABLE "app_notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_929b26168da1133020fec9dfc6"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_assettype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b9eafaf7b77cd42d38373baa6"`);
        await queryRunner.query(`DROP TABLE "income_sources"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a27359168c75df14b4dd4655f"`);
        await queryRunner.query(`DROP TABLE "budget_expenses"`);
        await queryRunner.query(`DROP TYPE "public"."budget_expenses_periodicity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_919faa73fd59efb0f80ccc3607"`);
        await queryRunner.query(`DROP TABLE "budget_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_431fac525c60f41aeed92bf55c"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50e41ba6f48cd56959d48b9891"`);
        await queryRunner.query(`DROP TABLE "credit_cards"`);
        await queryRunner.query(`DROP TYPE "public"."credit_cards_paymenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e70b8513c88f595b9f83749bcb"`);
        await queryRunner.query(`DROP TABLE "cuotas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0278fdedafa9ab24bfc0b0aa6e"`);
        await queryRunner.query(`DROP TABLE "debts"`);
        await queryRunner.query(`DROP TYPE "public"."debts_type_enum"`);
        await queryRunner.query(`DROP TABLE "expense_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee734c37dc94b8500d8a40d29f"`);
        await queryRunner.query(`DROP TABLE "emergency_funds"`);
        await queryRunner.query(`DROP TABLE "exchange_rates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cf0463d99c166546f7af395b5"`);
        await queryRunner.query(`DROP TABLE "house_currencies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4276c9fb53c98d03f15341ff26"`);
        await queryRunner.query(`DROP TABLE "loans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fe1108e5be68571ac19022783"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b78d4c319ee3a47c039bc8544c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97c66324f4b349a5aca2b564fb"`);
        await queryRunner.query(`DROP TABLE "household_expenses"`);
        await queryRunner.query(`DROP TYPE "public"."household_expenses_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4bbea81db025cc9549d5248d7"`);
        await queryRunner.query(`DROP TABLE "investments"`);
        await queryRunner.query(`DROP TYPE "public"."investments_currency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."investments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2f1125d451a51dc5c61a41459"`);
        await queryRunner.query(`DROP TABLE "net_worth_snapshots"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_items_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_lists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c3a113119a02c1d82cf269c5d"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41139b4264055882aa0675c208"`);
        await queryRunner.query(`DROP TABLE "recurring_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0c000b88df1ee31bbbeb5e24c"`);
        await queryRunner.query(`DROP TABLE "savings_goals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f24c67b2a439614e058bf5598a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d66471a99dd3836e1528d39a1e"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "houses"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
